### ISSUE TITLE
lhs always gets undefined in write()

### ISSUE THREAD

**Issue by Soulike** [Haiyang-Sun/nodeprof.js#101]
## Analysis

```js
this.write = (iid, name, val, lhs) =>
{
    console.log(`${name}: ${lhs} -> ${val}`);
};
```

## Code

```js
let variable = 1;
variable = variable + 1;
variable = variable + 1;
```

## Expected Output

```text
variable: undefined -> 1
variable: 1 -> 2
variable: 2 -> 3
```

## Actual Output

```text
variable: undefined -> 1
variable: undefined -> 2
variable: undefined -> 3
```

How can I get the value stored in the variable before the write operation?

**Comment by alexjordan** [comment]
Hi @Soulike,

as you can see in the [code](https://github.com/Haiyang-Sun/nodeprof.js/blob/master/src/ch.usi.inf.nodeprof/src/ch/usi/inf/nodeprof/jalangi/factory/WriteFactory.java#L53) reading the old value _before_ the write is not implemented.
