### ISSUE TITLE
Online instrumentation in the browser

### ISSUE THREAD

**Issue by GianlucaDeStefano** [Haiyang-Sun/nodeprof.js#107]
Hi, I would like to instrument online webpages and run analysis directly in the browser without having to pre-download the website's code locally. I was implementing this analysis using Jalangi, but since it does not support EC6 features I am trying to find an alternative tool. 

Do you think that nodeprof  is suited for this purpose? Does it support the instrumentation of frontend JS code (Js inlined with HTML)?

**Comment by Haiyang-Sun** [comment]
Hi @GianlucaDeStefano , nodeprof doesn't run in browser, so it won't help in your case.
