### ISSUE TITLE
Unsupported Jalangi features

### ISSUE THREAD

**Issue by aralisza** [Haiyang-Sun/nodeprof.js#26]
Hello,

My team is using nodeprof and we are interested in the `declare` and `endExpresion` callbacks that Jalangi has. Is this something that's in the works? If so, is there an estimated time for completion? If not, how difficult would you estimate it to be to implement?

Thanks in advance!

**Comment by Haiyang-Sun** [comment]
Hi, 

You can find the support for ```endExpression```  here: #27 , feel free to try it and give feedbacks.

To support ```declare```, some patch for instrumentation is needed at Graal.js side.  I'm a bit busy recently, but I can try to work on such a patch later this week. After it's integrated into Graal.js, I will release it here.

**Comment by aralisza** [comment]
Are there any updates about `declare` support?

**Comment by Haiyang-Sun** [comment]
The declare hook is now supported with the recent update https://github.com/Haiyang-Sun/nodeprof.js/commit/ccff3cafe350cba49af91a88bfa38b564a4e6aef
A basic ```endExpression``` hook has also been supported as discussed in #27
