### ISSUE TITLE
Upgrade to Graal VM 19

### ISSUE THREAD

**Issue by mtorp** [Haiyang-Sun/nodeprof.js#32]
Any chance that nodeprof.js can be updated to work with Graal19?
There are issues with regular expressions in the currently used version of Graal.

**Comment by alexjordan** [comment]
Hi Martin! We are aware that NodeProf currently does not work with the latest version of GraalVM, but we are working on it.

**Comment by Haiyang-Sun** [comment]
Hi Martin, to better solve the problem you met, could you please show some code snippet to reproduce the bug?

**Comment by mtorp** [comment]
> Hi Martin, to better solve the problem you met, could you please show some code snippet to reproduce the bug?

Certainly, but I believe the issue is related to Graal and not Node.js (See [https://github.com/graalvm/graaljs/issues/145](https://github.com/graalvm/graaljs/issues/145)).

If you want to see it reproduced with nodeprof, try to clone [https://github.com/jaredpalmer/formik](https://github.com/jaredpalmer/formik), install it, and run `mx -p $NODE_PROF_LOCATION jalangi --analysis ${ANALYSIS_LOC} npm test`
In general, I believe any invocation of the jest framework should reveal the error.

**Comment by mtorp** [comment]
Thanks for updating to the newest version of Graal.
The jest framework now runs flawlessly :)
