### ISSUE TITLE
Propagate signals to analysis

### ISSUE THREAD

**Issue by mtorp** [Haiyang-Sun/nodeprof.js#39]
Would it be possible to propagate signals sent to the running NodeProf/Graal to the NodeProf analysis.

For example, I would like to have the `endExecution` hook fire whenever I press ctrl-C.
```
process.on('SIGINT', () => {J$.analysis.endExecution()});
```

**Comment by alexjordan** [comment]
That handler should already be in place if you use `jalangi.js`.

https://github.com/Haiyang-Sun/nodeprof.js/blob/master/src/ch.usi.inf.nodeprof/js/jalangi.js#L187:
```
process.on('SIGINT', function(){
  process.exit();
});

process.on('exit', function () { J$.endExecution(); });
```

**Comment by mtorp** [comment]
Thanks. The 'exit' handler does seem to work, but the analysis responds quite slowly to interrupts. In our case it takes almost 30 seconds before the handler is executed.
