### ISSUE TITLE
how to record all write operations of a Node.js program

### ISSUE THREAD

**Issue by 598807302** [Haiyang-Sun/nodeprof.js#73]
As a newer, I wonder how can I record all operation write of a Node.js program.
E.g x = 3

**Comment by Haiyang-Sun** [comment]
Hi,

You can include the ```write``` callback in your analysis, such as:
```
    this.write = function(iid, name, val){
        console.log('write', J$.iidToLocation(iid), name, typeof(val));
    }
```

We have a test analysis including the write callback:
https://github.com/Haiyang-Sun/nodeprof.js/blob/master/src/ch.usi.inf.nodeprof/js/analysis/rw/analysis.js

**Comment by Haiyang-Sun** [comment]
You need to build nodeprof first, and then you can try this analysis with the following cmd in the nodeprof directory:

```mx jalangi --analysis src/ch.usi.inf.nodeprof/js/analysis/rw/analysis.js YOURTEST.js```

Or in the docker image release, you can run your test by replacing the example analysis with your analysis code:
```./bin/node --experimental-options --nodeprof ./nodeprof/nodeprof.js --analysis  ./nodeprof/examples/example.js ./nodeprof/tests/helloworld.js ```

**Comment by 598807302** [comment]
Thanks！ I will have a try！
