### ISSUE TITLE
mx build failed on ubuntu 18.04? openjdk version 1.8.0

### ISSUE THREAD

**Issue by dizhong** [Haiyang-Sun/nodeprof.js#8]
Hi, 

Part of the build seem to be failing on my machine with errors about files not existing, and/or some java errors. 

Screenshot of the error:
![image](https://user-images.githubusercontent.com/13694002/43966909-1ea283a8-9c91-11e8-864f-7ce270f63aa9.png)

Previously it was failing on creating a folder called src. I looked at the address the error was referring to, and noticed a file called "src" that contained a line of text "../../trufflenode/src/main/java" when clicked open. But it seemed like what was needed was a folder,  so I deleted the file and created a "src" folder by hand. That part seems to pass now, but I'm also pasting that error here for reference, in case it's relevant:
![image](https://user-images.githubusercontent.com/13694002/43967203-e1e76e96-9c91-11e8-88c6-aee862485a0b.png)

Thank you,

**Comment by Haiyang-Sun** [comment]
Hello,
Have you run ``` mx sforceimports ``` before running ```mx build```?

**Comment by dizhong** [comment]
Hi,
Yes, I have.

**Comment by Haiyang-Sun** [comment]
These bugs are related to the building of Graal.js, and it requires the following prerequisites (as shown in their guide: https://github.com/graalvm/graaljs/blob/master/graal-nodejs/BUILDING.md)
    gcc and g++ 4.9.4 or newer, or
    clang and clang++ 3.4.2 or newer (macOS: latest Xcode Command Line Tools)
    Python 2.6 or 2.7
    GNU Make 3.81 or newer

From the log, I guess it might be related to the default python version of your machine. Please make sure python refers to python 2.6 or 2.7, not newer versions.
If this does not solve your problem, try to use this JDK instead (https://github.com/graalvm/openjdk8-jvmci-builder/releases/download/jvmci-0.46/openjdk-8u172-jvmci-0.46-linux-amd64.tar.gz). Before building, export JAVA_HOME to the new jdk. 

Our tool is built and tested via the travis gate for every commit, here is the gate config: https://github.com/Haiyang-Sun/nodeprof.js/blob/master/.travis.yml

You can see the output for the last build here: https://travis-ci.com/Haiyang-Sun/nodeprof.js/builds/81507533 , maybe it can help you see the difference in the building.

Let me know if this helps :)

**Comment by Haiyang-Sun** [comment]
remember to do ```mx clean``` if you want to start a clean building from scratch.

**Comment by dizhong** [comment]
Thank you! It turned out that I didn't have clang installed. After installing clang and downloading a fresh copy of nodeprof, I was able to build and test it. :)

**Comment by LucaFranceschini** [comment]
> These bugs are related to the building of Graal.js, and it requires the following prerequisites (as shown in their guide: https://github.com/graalvm/graaljs/blob/master/graal-nodejs/BUILDING.md)
> gcc and g++ 4.9.4 or newer, or
> clang and clang++ 3.4.2 or newer (macOS: latest Xcode Command Line Tools)
> Python 2.6 or 2.7
> GNU Make 3.81 or newer
> 
> From the log, I guess it might be related to the default python version of your machine. Please make sure python refers to python 2.6 or 2.7, not newer versions.
> If this does not solve your problem, try to use this JDK instead (https://github.com/graalvm/openjdk8-jvmci-builder/releases/download/jvmci-0.46/openjdk-8u172-jvmci-0.46-linux-amd64.tar.gz). Before building, export JAVA_HOME to the new jdk.

I also faced issues similar to the OP. I had all those prerequisites, Python 2 and JDK 8. Still, the only way to make it work was to use that JDK. Maybe it is worth documenting it somewhere (readme?), since the resulting errors are not clear at all, and I only found the right suggestion in this closed issue.

**Comment by Haiyang-Sun** [comment]
I'm going to update the readme file about this.
